<button class="scalable" type="button" id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>" data-mage-init='{"Doddle_Returns/js/api-test":{
    "buttonId": "<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>",
    "successMessage": "<?= $block->escapeHtmlAttr(__($block->getSuccessMessage())) ?>",
    "failMessage": "<?= $block->escapeHtmlAttr(__($block->getFailMessage())) ?>"}, "validation": {}}'>
    <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
</button>
